### ISSUE TITLE
run_active type cast

### ISSUE THREAD

**Issue by shoover** [epics-modules/dxpSITORO#2]
Hi,

While reviewing a multi-module preset run time issue, I noticed there is one instance of getting run_active that uses the wrong type. This should be unsigned long like the others.

https://github.com/epics-modules/dxpSITORO/blob/7d3420ecf311ec7ef02a669e01aa061d64c05db1/dxpApp/src/NDDxp.cpp#L1052

**Comment by MarkRivers** [comment]
Fixed, thanks.  I also changed the variable name from run_active to runActive to be consistent with the rest of the file.
